---
version: 2
project_name: headlines
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
dockers:
  - image_templates: ["ghcr.io/shaharia-lab/headlines:{{ .Version }}"]
    dockerfile: goreleaser.dockerfile
    build_flag_templates:
      - --label=org.opencontainers.image.title={{ .ProjectName }}
      - --label=org.opencontainers.image.description={{ .ProjectName }}
      - --label=org.opencontainers.image.url=https://github.com/shaharia-lab/headlines
      - --label=org.opencontainers.image.source=https://github.com/shaharia-lab/headlines
      - --label=org.opencontainers.image.version={{ .Version }}
      - --label=org.opencontainers.image.revision={{ .FullCommit }}
      - --label=org.opencontainers.image.licenses=MIT
nfpms:
  - maintainer: Shaharia Lab OÜ <hello@shaharialab.com>
    description: Collect news headlines from different news sources
    homepage: https://github.com/shaharia-lab/headlines
    license: MIT
    formats:
      - deb
      - rpm
      - apk